# Generates src/lib/australia.ts, the map of the realm, from Natural Earth's
# 50m countries file (public domain). Run once when the map needs redrawing:
#
#   curl -L -o /tmp/ne50.geojson https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson
#   python3 scripts/build-map.py /tmp/ne50.geojson
#
# Coastal hatching (Tolkien's convention: short ticks on the sea side of the
# coast) and the mountain strokes are computed here, not drawn by hand.

import json, math, random, sys

random.seed(7)
src = sys.argv[1] if len(sys.argv) > 1 else '/tmp/ne50.geojson'
d = json.load(open(src))
feature = next(f for f in d['features'] if f['properties'].get('ADMIN') == 'Australia' or f['properties'].get('NAME') == 'Australia')
polys = [p[0] for p in feature['geometry']['coordinates']]

LNG0, LNG1, LAT0, LAT1 = 105.0, 160.0, -8.0, -46.0
W = 1000.0
k = math.cos(math.radians(27.0))
H = round(W * (LAT0 - LAT1) / ((LNG1 - LNG0) * k))


def proj(lng, lat):
    return ((lng - LNG0) / (LNG1 - LNG0) * W, (LAT0 - lat) / (LAT0 - LAT1) * H)


def path(pts):
    return 'M' + ' L'.join(f'{x:.1f} {y:.1f}' for x, y in pts) + ' Z'


def pip(pt, poly):
    x, y = pt
    inside = False
    n = len(poly)
    for i in range(n):
        x1, y1 = poly[i]
        x2, y2 = poly[(i + 1) % n]
        if (y1 > y) != (y2 > y):
            xi = x1 + (y - y1) * (x2 - x1) / (y2 - y1)
            if x < xi:
                inside = not inside
    return inside


land, hatch, hatch2 = [], [], []
for poly in polys:
    if len(poly) < 25:
        continue
    pts = [proj(lng, lat) for lng, lat in poly]
    if pts[0] == pts[-1]:
        pts = pts[:-1]
    land.append(path(pts))
    acc, step, n = 0.0, 13.0, len(pts)
    for i in range(n):
        x1, y1 = pts[i]
        x2, y2 = pts[(i + 1) % n]
        seg = math.hypot(x2 - x1, y2 - y1)
        if seg == 0:
            continue
        ux, uy = (x2 - x1) / seg, (y2 - y1) / seg
        t = step - acc
        while t < seg:
            px, py = x1 + ux * t, y1 + uy * t
            nx, ny = -uy, ux
            if pip((px + nx * 6, py + ny * 6), pts):
                nx, ny = -nx, -ny
            L = 6.0 + random.uniform(-1.5, 2.0)
            jitter = random.uniform(-0.6, 0.6)
            hatch.append(f'M{px:.1f} {py:.1f} l{nx * L + jitter:.1f} {ny * L:.1f}')
            hatch2.append(f'M{px + nx * 9.5:.1f} {py + ny * 9.5:.1f} l{nx * 3.2:.1f} {ny * 3.2:.1f}')
            t += step
        acc = (acc + seg) % step

ranges = [
    [(-16.5, 145.2), (-18.2, 145.6), (-20.5, 147.4), (-23.5, 148.5), (-26.2, 150.8), (-28.4, 152.3), (-30.5, 151.6), (-32.6, 150.9), (-34.2, 149.7), (-35.9, 148.4), (-37.4, 146.9)],
    [(-31.2, 138.6), (-32.4, 138.4)],
    [(-23.7, 132.8), (-23.8, 134.2)],
    [(-42.0, 146.2), (-42.9, 146.4)],
    [(-31.0, 116.5), (-32.5, 116.4)],
]
mounts = []
for r in ranges:
    for i in range(len(r) - 1):
        (la1, lo1), (la2, lo2) = r[i], r[i + 1]
        for s in range(3):
            f_ = s / 3
            lng = lo1 + (lo2 - lo1) * f_ + random.uniform(-0.3, 0.3)
            lat = la1 + (la2 - la1) * f_ + random.uniform(-0.2, 0.2)
            x, y = proj(lng, lat)
            w = random.uniform(5, 8)
            h = random.uniform(6, 10)
            mounts.append(f'M{x - w:.1f} {y + h * 0.55:.1f} L{x:.1f} {y - h * 0.45:.1f} L{x + w:.1f} {y + h * 0.55:.1f} M{x:.1f} {y - h * 0.45:.1f} L{x + w * 0.35:.1f} {y + h * 0.3:.1f}')

seas = {
    'Indian Ocean': (-27.5, 110.0),
    'Southern Ocean': (-43.0, 132.0),
    'Tasman Sea': (-38.5, 155.0),
    'Coral Sea': (-17.0, 152.5),
    'Timor Sea': (-11.5, 127.0),
    'Great Australian Bight': (-35.5, 131.5),
}
out = [
    '// Generated by scripts/build-map.py from Natural Earth 50m (public domain).',
    '// The coast of Australia projected for the map of the realm. Do not edit by hand.',
    f'export const MAP_W = {int(W)};',
    f'export const MAP_H = {H};',
    f'export const MAP_BOUNDS = {{ lng0: {LNG0}, lng1: {LNG1}, lat0: {LAT0}, lat1: {LAT1} }};',
    'export const LAND: string[] = ' + json.dumps(land) + ';',
    'export const HATCH = ' + json.dumps(' '.join(hatch)) + ';',
    'export const HATCH_2 = ' + json.dumps(' '.join(hatch2)) + ';',
    'export const MOUNTAINS = ' + json.dumps(' '.join(mounts)) + ';',
    'export const SEAS: { name: string; x: number; y: number }[] = ' + json.dumps([{'name': n, 'x': round(proj(lo, la)[0], 1), 'y': round(proj(lo, la)[1], 1)} for n, (la, lo) in seas.items()]) + ';',
]
open('src/lib/australia.ts', 'w').write('\n'.join(out) + '\n')
print(f'wrote src/lib/australia.ts: {len(land)} land masses, {len(hatch)} hatch ticks, {len(mounts)} mountain strokes')
